### ISSUE TITLE
[Suggestion] Less than 6 letter words

### ISSUE THREAD

**Issue by Pandaptable** [davidbmaier/discord-recap#11]
Not sure how hard this would be to implement or anything; but I think it'd be great to be able to see more most used words, instead of only 6 letters or more. I can't grasp the fact that my most used word is "fucking" throughout every single year since 2015 on discord. 3 or 4 letter words would be nice to see, anything less is pointless. The best implementation from my perspective is having just a toggle to change it to a different number, or maybe a slider to change it? Slider could have it be even bigger than 6 if wanted.

also, thank you for getting to the last suggestion, github didn't seem to properly notify me so I never saw it.

**Comment by davidbmaier** [comment]
A slider is probably not gonna happen, because it would require a bunch of real-time analysis of all messages every time you change it. There are definitely some possible solutions to that, but I don't really want to make the stats configurable in that way.

I added the "6 letters" restriction originally because https://ddpe.androz2091.fr/ is using it too (and people were always gonna test both services and complain about mismatches), and because I initially had no restriction at all, which was pretty useless.

I'll play around with a lower global restriction and maybe some extra logic, will update this issue when I've got a solution.

**Comment by davidbmaier** [comment]
Alright, I did some testing and I decided to just leave it at 6+, sorry. In my experience, everything below that just contains the same words in every channel and DM, making the whole thing somewhat useless. Of course that might be skewed since I'm only looking at my own data, but for my data it loses any meaning. See the image below:
![image](https://user-images.githubusercontent.com/17618532/179741695-9e18446a-ccae-4baf-b566-71160e014ce4.png)

Some technical background why I don't want to make it configurable:
Either the initial analysis step would need to collect several sets of word data, likely blowing up the data footprint of the data that gets stored in the browser (since it gets computed for each server, channel, DM etc.) - or I would need the browser to store literally all the user's messages to compute it on the fly, which is definitely not something I want to do either.

I could just collect some specific sets (like words with 3+, 6+ and 10+ characters), but they're very arbitrary and would still increase the data footprint - this is probably the only option I'd be somewhat okay with, but I'm not really happy with it either.
If more people ask for it, I might look into it. Right now I'm alright with the restriction.
