### ISSUE TITLE
Error - Cannot read properties of null

### ISSUE THREAD

**Issue by nmsturcke** [davidbmaier/discord-recap#12]
I am getting the following error when trying to analyze my package:

![image](https://user-images.githubusercontent.com/30734036/185379887-61ddf0f5-f008-4da8-bf89-00dce46db1be.png)

**Comment by davidbmaier** [comment]
Hmm, looks like an issue with trying to parse the messages of a channel - I can't reproduce it locally because it's probably something specific with your package.
But I think there might be a channel in the package that has no messages (maybe because all the messages you've sent in there got deleted later?). Not sure what exactly is going on, but I have an idea for a fix - will take a closer look later today.

**Comment by davidbmaier** [comment]
Alright, I managed to reproduce it by breaking a data package of my own and removing a messages file. Really not sure why that happens considering empty channel message files are fine - so for some reason the file must just be missing?
The fact that you're the first one running into this problem might mean that either something went wrong with your packages specifically, or if you've recently requested your data maybe something just changed in the format. I've just requested my data again to check.

In any case, I updated the live version with a tiny fix that just ignores missing files and doesn't try to parse them further (which is where your error happened).
@nmsturcke Please take a look at https://discord-recap.com and try if the latest version works fine for you now. If the parsing works fine, definitely also check if the displayed data looks alright.

**Comment by nmsturcke** [comment]
Works now, thanks
